language: objective-c
before_install:
  - brew update
install:
  - cp --parents $PWD/Formula/hs.rb $(brew --repo)/Library/Taps/hotshell/Formula/
  - brew tap --repair
script:
  - brew audit hs
  - brew install -v hs
  - brew test hs
