language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/hotshell
  - brew tap --repair
script:
  - brew audit hs
  - brew install -v hotshell/hs
  - brew test hs
