language: objective-c
before_install:
  - brew update
install:
  - cp -p $PWD/Formula/hs.rb $(brew --repo)/Library/Taps/hotshell/Formula/
script:
  - brew audit hs
  - brew install -v hs
  - brew test hs
