language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/julienmoumne/hotshell/Formula
  - cp $PWD/Formula/hs.rb $(brew --repo)/Library/Taps/julienmoumne/hotshell/Formula/
  - brew tap --repair
script:
  - brew audit hs
  - brew install -v hs
  - brew test hs
